In [32]:
from keras.models import Model, Sequential, load_model
from keras.optimizers import Nadam, SGD, Adam
from keras.layers import Conv2D, MaxPooling2D, Input, Conv1D, MaxPooling3D, Conv3D, ConvLSTM2D, LSTM, AveragePooling2D
from keras.layers import Input, LSTM, Embedding, Dense, LeakyReLU, Flatten, Dropout, SeparableConv2D, GlobalAveragePooling3D
from keras.layers import TimeDistributed, BatchNormalization
from keras import optimizers
from keras.callbacks import EarlyStopping
from keras import regularizers
import pandas as pd
import numpy as np
from numpy import zeros, newaxis
from sklearn import metrics
from sklearn.metrics import mean_squared_error
from math import sqrt
import tensorflow as tf

In [35]:
df1 = pd.read_csv("SoilMoiPreProcessed2015.csv",header=None)
df2 = pd.read_csv("SoilMoiPreProcessed2016.csv",header=None)
df3 = pd.read_csv("SoilMoiPreProcessed2017.csv",header=None)
df4 = pd.read_csv("SoilMoiPreProcessed2018.csv",header=None)
df5 = pd.read_csv("SoilMoiPreProcessed2019.csv",header=None)

In [10]:
df3.head()

0          1          2   ...         44         45         46
0  58.270000  56.132000  52.604000  ...  56.736000  55.038998  52.942001
1  41.310001  39.239998  43.724998  ...  49.830002  48.070999  45.570999
2  55.883999  54.286999  50.931999  ...  59.243999  57.928001  56.349998
3  57.676998  55.741001  51.415001  ...  65.436996  62.813999  60.724998
4  57.630001  55.697998  52.355000  ...  60.564999  58.799999  56.635998

[5 rows x 47 columns]

In [11]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 47 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       100 non-null    float64
 1   1       100 non-null    float64
 2   2       100 non-null    float64
 3   3       100 non-null    float64
 4   4       100 non-null    float64
 5   5       100 non-null    float64
 6   6       100 non-null    float64
 7   7       100 non-null    float64
 8   8       100 non-null    float64
 9   9       100 non-null    float64
 10  10      100 non-null    float64
 11  11      100 non-null    float64
 12  12      100 non-null    float64
 13  13      100 non-null    float64
 14  14      100 non-null    float64
 15  15      100 non-null    float64
 16  16      100 non-null    float64
 17  17      100 non-null    float64
 18  18      100 non-null    float64
 19  19      100 non-null    float64
 20  20      100 non-null    float64
 21  21      100 non-null    float64
 22  22 

In [12]:
df1.to_numpy()
df2.to_numpy()
df3.to_numpy()
df4.to_numpy()


array([[52.70999908, 50.82699966, 47.47200012, ..., 59.0870018 ,
        57.37900162, 55.16699982],
       [45.10699844, 42.89199829, 39.09700012, ..., 56.26900101,
        54.79499817, 52.53300095],
       [56.15499878, 54.64199829, 51.91199875, ..., 60.09999847,
        58.86299896, 57.01100159],
       ...,
       [39.66199875, 37.09000015, 33.02799988, ..., 59.14500046,
        57.11399841, 54.18999863],
       [55.07299805, 53.18700027, 49.85200119, ..., 53.06600189,
        51.22200012, 48.93600082],
       [48.75099945, 45.89400101, 41.0890007 , ..., 58.09199905,
        56.1570015 , 53.2879982 ]])

In [36]:
df5.to_numpy()

array([[54.66500092, 52.11100006, 54.0019989 , ..., 55.74100113,
        55.51599884, 53.46910477],
       [51.9659996 , 49.31900024, 49.93799973, ..., 62.38499832,
        60.3030014 , 55.79510117],
       [56.59000015, 54.52899933, 53.34899902, ..., 56.98540878,
        56.76699829, 55.47810364],
       ...,
       [53.50600052, 50.40299988, 58.68999863, ..., 44.01800156,
        43.87599945, 42.25110245],
       [48.43700027, 45.91899872, 62.13899994, ..., 80.90724182,
        74.56800079, 70.81909943],
       [52.60900116, 49.39400101, 48.92699814, ..., 47.12099838,
        46.91699982, 44.98810196]])

In [13]:
 df1=np.asarray(df1).reshape(47,1,100,1)
 df2=np.asarray(df2).reshape(47,1,100,1)
 df3=np.asarray(df3).reshape(47,1,100,1)
 df4=np.asarray(df4).reshape(47,1,100,1)


In [37]:
 df5=np.asarray(df5).reshape(47,1,100,1)


In [14]:
a1rr=[]

In [15]:
a1rr.append(df1)
a1rr.append(df2)
a1rr.append(df3)
a1rr.append(df4)


In [38]:
test=[]
test.append(df5)

In [39]:
test=np.array(test)

In [16]:
a1rr

[array([[[[65.13534546],
          [61.17545319],
          [68.21800232],
          ...,
          [63.61600113],
          [61.95600128],
          [59.78330231]]],
 
 
        [[[53.22431946],
          [74.61547852],
          [68.06401062],
          ...,
          [65.85830688],
          [57.30754852],
          [57.25194168]]],
 
 
        [[[52.63008499],
          [50.11564636],
          [48.22653961],
          ...,
          [56.04994965],
          [52.97000122],
          [51.02500153]]],
 
 
        ...,
 
 
        [[[94.22000122],
          [88.8030014 ],
          [84.18099976],
          ...,
          [94.86599731],
          [88.44599915],
          [75.22499847]]],
 
 
        [[[74.22299957],
          [65.3219986 ],
          [60.12599945],
          ...,
          [68.04599762],
          [67.19999695],
          [63.06399918]]],
 
 
        [[[60.0909996 ],
          [57.83900452],
          [57.64500809],
          ...,
          [54.28300095],
          [51

In [17]:
a1rr=np.array(a1rr)

In [18]:
a1rr.shape

(4, 47, 1, 100, 1)

In [19]:
y = np.array([224.2, 254.3, 300.56,357.19])


In [20]:
y.shape

(4,)

In [40]:
test.shape

(1, 47, 1, 100, 1)

In [58]:
def CNN_LSTM(frames, location, features):

        frames_input = Input(shape=(frames, 1, location, features))
        vision_model = Sequential()
        vision_model.add(Conv2D(64, (1, 2), activation='relu', padding='same', input_shape=(1, location, features)))
        vision_model.add(BatchNormalization())
        vision_model.add(MaxPooling2D((1, 2)))
        vision_model.add(Flatten())
        vision_model.add(BatchNormalization())
        encoded_frame_sequence = TimeDistributed(vision_model)(frames_input) # the output will be a sequence of vectors
        encoded_video = LSTM(256, activation='tanh', return_sequences=True)(encoded_frame_sequence)  # the output will be a vector
        
        fc2 = Dense(64, activation='relu', kernel_regularizer=regularizers.l2(0.05))(encoded_video)
        out = Flatten()(fc2)
        out = Dropout(0.5)(out)
        output = Dense(1, activation='relu')(out)
        CNN_LSTM = Model(inputs=frames_input, outputs=output)
        return CNN_LSTM



In [59]:
model = CNN_LSTM(47,100,1)

In [60]:
model.summary()

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         (None, 47, 1, 100, 1)     0         
_________________________________________________________________
time_distributed_4 (TimeDist (None, 47, 3200)          13248     
_________________________________________________________________
lstm_4 (LSTM)                (None, 47, 256)           3539968   
_________________________________________________________________
dense_7 (Dense)              (None, 47, 64)            16448     
_________________________________________________________________
flatten_8 (Flatten)          (None, 3008)              0         
_________________________________________________________________
dropout_4 (Dropout)          (None, 3008)              0         
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 3009

In [61]:
model.compile(
    optimizer='sgd',
    loss='mse',
    metrics=[tf.keras.metrics.RootMeanSquaredError()])

In [64]:
model.fit(a1rr, y,epochs = 25)


Epoch 1/25
4/4 [==============================] - 2s 472ms/step - loss: 5602.7295 - root_mean_squared_error: 210.7005
Epoch 2/25
4/4 [==============================] - 2s 450ms/step - loss: 5056642048.0000 - root_mean_squared_error: 41055.7656
Epoch 3/25
4/4 [==============================] - 2s 428ms/step - loss: 133761482752.0000 - root_mean_squared_error: 35555.6289
Epoch 4/25
4/4 [==============================] - 2s 447ms/step - loss: 133494136832.0000 - root_mean_squared_error: 31802.1836
Epoch 5/25
4/4 [==============================] - 2s 441ms/step - loss: 133227274240.0000 - root_mean_squared_error: 29031.5273
Epoch 6/25
4/4 [==============================] - 2s 447ms/step - loss: 132960911360.0000 - root_mean_squared_error: 26878.1934
Epoch 7/25
4/4 [==============================] - 2s 429ms/step - loss: 132695146496.0000 - root_mean_squared_error: 25142.4570
Epoch 8/25
4/4 [==============================] - 2s 441ms/step - loss: 132429881344.0000 - root_mean_squared_error:

In [63]:
model.predict(test)

array([[117.812355]], dtype=float32)

In [51]:
model.weights

[<tf.Variable 'conv2d_2/kernel:0' shape=(1, 2, 1, 64) dtype=float32, numpy=
 array([[[[-3.73141813e+00,  1.44239277e-01, -8.51393738e+01,
            1.00635176e+01, -4.83147097e+00, -3.86218488e-01,
           -4.51766670e-01, -1.03122547e-01,  1.62892890e+00,
           -1.26631677e+00,  4.93960202e-01, -9.73426700e-02,
           -1.82439613e+00,  1.97052136e-02, -1.21504568e-01,
           -5.92936401e+02, -3.64042807e+00, -4.34899426e+00,
           -4.77587044e-01, -1.09377170e+00, -1.84610412e-01,
           -8.49930942e-02,  5.70250563e-02, -6.80947751e-02,
            1.03763742e+01,  1.09488294e-01, -8.77537280e-02,
            4.11927795e+00, -1.18855037e-01,  4.60361242e-01,
           -5.49063087e-02, -1.94712937e-01, -4.85674620e-01,
           -1.05759120e+00,  5.43513931e-02, -5.67983508e-01,
            2.93228962e-02, -8.42402577e-02, -1.11615896e+01,
           -3.68551165e-02, -5.99537992e+00, -8.81633568e+00,
            1.62732983e+00, -5.63904643e-01, -1.02383339